project:
  type: website

website:
  title: "Félix Puémape"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: research/index.qmd
        text: Research
      - href: teaching/index.qmd
        text: Teaching
  page-footer:
    left: "© 2025 Félix Puémape"
    right:
      - icon: twitter
        href: https://twitter.com/fpuemape
      - icon: envelope
        href: mailto:felix.puemape@gmail.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

metadata-files: [docs/CNAME]

