project:
  type: website
  resources:
    - CNAME

website:
  title: "Felix Puemape"
  site-url: "https://www.felixpuemape.com"
  favicon: favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: teaching/index.qmd
        text: Teaching
      - href: cv/index.qmd
        text: CV
  google-analytics: "G-F57WQLHH67"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

metadata:
  og:title: "Felix Puemape -"
  og:site-name: "Felix Puemape"
  og:image: "https://www.felixpuemape.com/felix.jpg"
  twitter:title: "Felix Puemape -"
  twitter:card: "summary_large_image"
  twitter:image: "https://www.felixpuemape.com/profile-tw.png"
  twitter:creator: "@felixpuemape"

editor: source